# Generated by Django 2.1 on 2019-02-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField(blank=True, null=True)),
                ('lastname', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.TextField(blank=True, null=True)),
                ('check', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True, unique=True)),
                ('country', models.TextField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
