# Generated by Django 2.1 on 2019-02-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
    ]
