# Generated by Django 3.2.4 on 2021-06-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createuser', '0002_auto_20190227_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='check',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
    ]
