# Generated by Django 3.2.4 on 2021-06-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createuser', '0003_auto_20210622_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignTaskFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_Name', models.TextField(blank=True, null=True)),
                ('Task_level', models.TextField(blank=True, null=True)),
                ('Priority', models.TextField(blank=True, null=True)),
                ('Created_Date', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('Action', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
