# Generated by Django 3.2.4 on 2021-06-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createuser', '0005_remove_userprofile_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('role', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='objectLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackId', models.TextField(blank=True, null=True)),
                ('objectClass', models.TextField(blank=True, null=True)),
                ('occlusion', models.TextField(blank=True, null=True)),
                ('pose', models.TextField(blank=True, null=True)),
                ('lane_change', models.BooleanField(blank=True, null=True)),
                ('breakLight', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SceneLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Light_Condition', models.TextField(blank=True, null=True)),
                ('Road_Type', models.TextField(blank=True, null=True)),
                ('Road_works', models.TextField(blank=True, null=True)),
                ('Tunnel', models.TextField(blank=True, null=True)),
                ('Weather', models.TextField(blank=True, null=True)),
                ('Street_Condition', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.TextField(blank=True),
        ),
    ]
