# Generated by Django 3.2.4 on 2021-07-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createuser', '0006_auto_20210628_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.TextField(blank=True, null=True)),
                ('project_Feature', models.TextField(blank=True, null=True)),
                ('Tool_version', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
