# Generated by Django 3.2.4 on 2021-07-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createuser', '0007_projectfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigntaskfiles',
            name='project_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
