# Generated by Django 3.2.4 on 2021-07-16 18:27

import createuser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createuser', '0009_objectcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigntaskfiles',
            name='annotation_image',
            field=models.ImageField(blank=True, null=True, upload_to=createuser.models.upload_path),
        ),
        migrations.AlterField(
            model_name='assigntaskfiles',
            name='File_Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assigntaskfiles',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loginprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='objectcategories',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='objectlevel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectfiles',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scenelevel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
